name: streaming_videocall_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.1
  flutter_webrtc: ^0.10.6
  socket_io_client: ^2.0.3+1
  provider: ^6.1.2
  firebase_core: ^2.31.1
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
