// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgex18tc1Lr45KLHtDKx9Am0eRFrQ7lU',
    appId: '1:489404691962:web:a537a2f1939f3484d96043',
    messagingSenderId: '489404691962',
    projectId: 'videocall-d81cd',
    authDomain: 'videocall-d81cd.firebaseapp.com',
    storageBucket: 'videocall-d81cd.appspot.com',
    measurementId: 'G-M9ZJKETZNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfiOWzB70iq4EVYkav8EMLUHNN1ZI9S_E',
    appId: '1:489404691962:android:d130e6ef03fce4edd96043',
    messagingSenderId: '489404691962',
    projectId: 'videocall-d81cd',
    storageBucket: 'videocall-d81cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4EeA4hBnWNI8lTpSqy0vMWWex4CPbes',
    appId: '1:489404691962:ios:44312c4fcde25d6dd96043',
    messagingSenderId: '489404691962',
    projectId: 'videocall-d81cd',
    storageBucket: 'videocall-d81cd.appspot.com',
    iosBundleId: 'com.example.streamingVideocallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4EeA4hBnWNI8lTpSqy0vMWWex4CPbes',
    appId: '1:489404691962:ios:44312c4fcde25d6dd96043',
    messagingSenderId: '489404691962',
    projectId: 'videocall-d81cd',
    storageBucket: 'videocall-d81cd.appspot.com',
    iosBundleId: 'com.example.streamingVideocallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgex18tc1Lr45KLHtDKx9Am0eRFrQ7lU',
    appId: '1:489404691962:web:15df8e91993267fdd96043',
    messagingSenderId: '489404691962',
    projectId: 'videocall-d81cd',
    authDomain: 'videocall-d81cd.firebaseapp.com',
    storageBucket: 'videocall-d81cd.appspot.com',
    measurementId: 'G-43HP9GY7DB',
  );
}
